///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SupportSiteDemo2.SearchActions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchForArticle recording.
    /// </summary>
    [TestModule("a490351a-bd55-434c-bd2c-b8876b112164", ModuleType.Recording, 1)]
    public partial class SearchForArticle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SupportSiteDemo2.SupportSiteDemo2Repository repository.
        /// </summary>
        public static global::SupportSiteDemo2.SupportSiteDemo2Repository repo = global::SupportSiteDemo2.SupportSiteDemo2Repository.Instance;

        static SearchForArticle instance = new SearchForArticle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchForArticle()
        {
            searchTerm = "selenium";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchForArticle Instance
        {
            get { return instance; }
        }

#region Variables

        string _searchTerm;

        /// <summary>
        /// Gets or sets the value of variable searchTerm.
        /// </summary>
        [TestVariable("fb8774ed-e8d1-4d01-a6e3-9f077c56bdbe")]
        public string searchTerm
        {
            get { return _searchTerm; }
            set { _searchTerm = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SearchInput' at 109;16.", repo.ApplicationUnderTest.SearchInputInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SearchInput.Click("109;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$searchTerm' with focus on 'ApplicationUnderTest.SearchInput'.", repo.ApplicationUnderTest.SearchInputInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SearchInput.PressKeys(searchTerm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.SearchInput'.", repo.ApplicationUnderTest.SearchInputInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SearchInput.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
