///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SupportSiteDemo2.SearchActions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateOnArticle recording.
    /// </summary>
    [TestModule("5e7992f4-1f52-414b-a542-8b4d6f9f01a3", ModuleType.Recording, 1)]
    public partial class ValidateOnArticle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SupportSiteDemo2.SupportSiteDemo2Repository repository.
        /// </summary>
        public static global::SupportSiteDemo2.SupportSiteDemo2Repository repo = global::SupportSiteDemo2.SupportSiteDemo2Repository.Instance;

        static ValidateOnArticle instance = new ValidateOnArticle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateOnArticle()
        {
            articleTitle = "Selenium WebDriver integration";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateOnArticle Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable articleTitle.
        /// </summary>
        [TestVariable("ddf79e13-ef68-420b-a142-0c27b8bfd5d6")]
        public string articleTitle
        {
            get { return repo.articleTitle; }
            set { repo.articleTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.ArticleTitle'.", repo.ApplicationUnderTest.ArticleTitleInfo, new RecordItemIndex(0));
            Validate.Exists(repo.ApplicationUnderTest.ArticleTitleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HomeLogo' at Center.", repo.ApplicationUnderTest.HomeLogoInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.HomeLogo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.HomePageTitle'.", repo.ApplicationUnderTest.HomePageTitleInfo, new RecordItemIndex(2));
            Validate.Exists(repo.ApplicationUnderTest.HomePageTitleInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
