///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SupportSiteDemo2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SupportSiteDemo2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1b4da351-7c31-42b2-86a4-813cef83008f")]
    public partial class SupportSiteDemo2Repository : RepoGenBaseFolder
    {
        static SupportSiteDemo2Repository instance = new SupportSiteDemo2Repository();
        SupportSiteDemo2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the SupportSiteDemo2Repository element repository.
        /// </summary>
        [RepositoryFolder("1b4da351-7c31-42b2-86a4-813cef83008f")]
        public static SupportSiteDemo2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SupportSiteDemo2Repository() 
            : base("SupportSiteDemo2Repository", "/", null, 0, false, "1b4da351-7c31-42b2-86a4-813cef83008f", ".\\RepositoryImages\\SupportSiteDemo2Repository1b4da351.rximgres")
        {
            _applicationundertest = new SupportSiteDemo2RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _firstText = "follows: Java (for  Grid):";

        /// <summary>
        /// Gets or sets the value of variable firstText.
        /// </summary>
        [TestVariable("bd0189c8-39ad-4555-885a-f92378fb3469")]
        public string firstText
        {
            get { return _firstText; }
            set { _firstText = value; }
        }

        string _href = "    ";

        /// <summary>
        /// Gets or sets the value of variable href.
        /// </summary>
        [TestVariable("af552e86-1c5d-4071-88aa-a6ebf514a417")]
        public string href
        {
            get { return _href; }
            set { _href = value; }
        }

        string _PopArticleTitle = "article-title";

        /// <summary>
        /// Gets or sets the value of variable PopArticleTitle.
        /// </summary>
        [TestVariable("8040858a-3ec6-43e0-b344-b7a199ead36a")]
        public string PopArticleTitle
        {
            get { return _PopArticleTitle; }
            set { _PopArticleTitle = value; }
        }

        string _LearnMoreItemH4 = "Getting Started";

        /// <summary>
        /// Gets or sets the value of variable LearnMoreItemH4.
        /// </summary>
        [TestVariable("4b676893-8b65-46fd-98af-e1c04c98feca")]
        public string LearnMoreItemH4
        {
            get { return _LearnMoreItemH4; }
            set { _LearnMoreItemH4 = value; }
        }

        string _LeftNavButtonItem = "Ranorex Studio";

        /// <summary>
        /// Gets or sets the value of variable LeftNavButtonItem.
        /// </summary>
        [TestVariable("dde207fe-ab5e-4878-b9f8-1663abebc5c0")]
        public string LeftNavButtonItem
        {
            get { return _LeftNavButtonItem; }
            set { _LeftNavButtonItem = value; }
        }

        string _LeftNavSubArticleLink = "Ranorex Studio start page";

        /// <summary>
        /// Gets or sets the value of variable LeftNavSubArticleLink.
        /// </summary>
        [TestVariable("85f57120-93c3-4259-907e-e49c216773a0")]
        public string LeftNavSubArticleLink
        {
            get { return _LeftNavSubArticleLink; }
            set { _LeftNavSubArticleLink = value; }
        }

        string _articleTitle = "Selenium WebDriver integration";

        /// <summary>
        /// Gets or sets the value of variable articleTitle.
        /// </summary>
        [TestVariable("172f1c1c-4003-430b-9d01-d9cd06797490")]
        public string articleTitle
        {
            get { return _articleTitle; }
            set { _articleTitle = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1b4da351-7c31-42b2-86a4-813cef83008f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("953d5c82-4830-487e-999f-8f8829627372")]
        public virtual SupportSiteDemo2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SupportSiteDemo2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("953d5c82-4830-487e-999f-8f8829627372")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchinputInfo;
            RepoItemInfo _firstresulttitleInfo;
            RepoItemInfo _articletitleInfo;
            RepoItemInfo _homelogoInfo;
            RepoItemInfo _homepagetitleInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='support.ranorex.com']", parentFolder, 30000, null, false, "953d5c82-4830-487e-999f-8f8829627372", "")
            {
                _searchinputInfo = new RepoItemInfo(this, "SearchInput", ".//div[@class='search-bar-wrapper']//input[@id='query']", "", 30000, null, "e8928d0f-e1fa-456c-8228-64bec3ce322d");
                _firstresulttitleInfo = new RepoItemInfo(this, "FirstResultTitle", ".//ul/li[1]/a/h3", "", 30000, null, "9f0e450e-805f-47be-8ee0-5716e04bdb57");
                _articletitleInfo = new RepoItemInfo(this, "ArticleTitle", ".//h1[@title=$articleTitle]", "", 30000, null, "f7b42dfb-9bc0-4f06-99d7-9e44291ec341");
                _homelogoInfo = new RepoItemInfo(this, "HomeLogo", ".//div[@class='logo']/a[@title='Home']", "element", 30000, null, "f3769a43-ea26-4645-87f1-9b4e04c00f67");
                _homepagetitleInfo = new RepoItemInfo(this, "HomePageTitle", ".//section[@class='hero-section']/h1", "element", 30000, null, "617822b8-335c-488f-8592-fa03f66cd4ce");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("953d5c82-4830-487e-999f-8f8829627372")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("953d5c82-4830-487e-999f-8f8829627372")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchInput item.
            /// </summary>
            [RepositoryItem("e8928d0f-e1fa-456c-8228-64bec3ce322d")]
            public virtual Ranorex.InputTag SearchInput
            {
                get
                {
                    return _searchinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchInput item info.
            /// </summary>
            [RepositoryItemInfo("e8928d0f-e1fa-456c-8228-64bec3ce322d")]
            public virtual RepoItemInfo SearchInputInfo
            {
                get
                {
                    return _searchinputInfo;
                }
            }

            /// <summary>
            /// The FirstResultTitle item.
            /// </summary>
            [RepositoryItem("9f0e450e-805f-47be-8ee0-5716e04bdb57")]
            public virtual Ranorex.H3Tag FirstResultTitle
            {
                get
                {
                    return _firstresulttitleInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The FirstResultTitle item info.
            /// </summary>
            [RepositoryItemInfo("9f0e450e-805f-47be-8ee0-5716e04bdb57")]
            public virtual RepoItemInfo FirstResultTitleInfo
            {
                get
                {
                    return _firstresulttitleInfo;
                }
            }

            /// <summary>
            /// The ArticleTitle item.
            /// </summary>
            [RepositoryItem("f7b42dfb-9bc0-4f06-99d7-9e44291ec341")]
            public virtual Ranorex.H1Tag ArticleTitle
            {
                get
                {
                    return _articletitleInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The ArticleTitle item info.
            /// </summary>
            [RepositoryItemInfo("f7b42dfb-9bc0-4f06-99d7-9e44291ec341")]
            public virtual RepoItemInfo ArticleTitleInfo
            {
                get
                {
                    return _articletitleInfo;
                }
            }

            /// <summary>
            /// The HomeLogo item.
            /// </summary>
            [RepositoryItem("f3769a43-ea26-4645-87f1-9b4e04c00f67")]
            public virtual Ranorex.ATag HomeLogo
            {
                get
                {
                    return _homelogoInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HomeLogo item info.
            /// </summary>
            [RepositoryItemInfo("f3769a43-ea26-4645-87f1-9b4e04c00f67")]
            public virtual RepoItemInfo HomeLogoInfo
            {
                get
                {
                    return _homelogoInfo;
                }
            }

            /// <summary>
            /// The HomePageTitle item.
            /// </summary>
            [RepositoryItem("617822b8-335c-488f-8592-fa03f66cd4ce")]
            public virtual Ranorex.H1Tag HomePageTitle
            {
                get
                {
                    return _homepagetitleInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The HomePageTitle item info.
            /// </summary>
            [RepositoryItemInfo("617822b8-335c-488f-8592-fa03f66cd4ce")]
            public virtual RepoItemInfo HomePageTitleInfo
            {
                get
                {
                    return _homepagetitleInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
