name: RanorexGitHubActionsDemo # Choose a name that makes the most sense to you 
 
on: # This setup will run the workflow on Push and Pull requests to the main code branch 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
 
jobs: 
 
  build: 
    strategy: 
      matrix: 
        configuration: [Debug] 
 
    runs-on: self-hosted # The Runner must be self-hosted 
     
    # Configure environment variables 
    env: 
      Solution_Name: SupportSiteDemo.sln # Replace with your solution name 
      Test_Project_Path: SupportSiteDemo2\SupportSiteDemo2.csproj # Replace with the path to your test project 
       
    # Check out code from the repository 
    steps: 
    - name: Checkout 
      uses: actions/checkout@v4 # At the time of writing, v4 is the latest 
      with: 
        fetch-depth: 0 

    # Removes files blocked by Windows after downloading from the internet
    - name: Unblock files
      shell: powershell
      run: Get-ChildItem -Recurse | Unblock-File    
 
    # Allows PowerShell scripts to run for this job without changing machine-wide policy.    
    - name: Allow PowerShell scripts
      shell: powershell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass   
 
    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild 
    - name: Setup MSBuild.exe 
      uses: microsoft/setup-msbuild@v2 # At the time of writing, v2 is the latest 

    # Clears previous build outputs to ensure a clean build from scratch.
    - name: Clean Solution
      run: msbuild $env:Solution_Name /t:Clean /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
 
    # This step is not required for all solutions 
    # Restore the application to populate the obj folder with RuntimeIdentifiers 
    - name: Restore the application 
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration 
      env: 
        Configuration: ${{ matrix.configuration }} 
 
    # Build the solution 
    - name: Build solution 
      run: msbuild $env:Solution_Name 
    
    # Run the solution, replacing RxDemoApp with the name of your solution 
    - name: Run the Test Suite 
      shell: powershell
      run: ".\\SupportSiteDemo2\\bin\\Debug\\ProjectSupportSiteDemo.exe"
